/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharesShareTokenRouteImport } from './routes/shares.$shareToken'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces.index'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces.$workspaceId.index'
import { Route as AuthenticatedWorkspacesWorkspaceIdTabRouteImport } from './routes/_authenticated/workspaces.$workspaceId.$tab'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharesShareTokenRoute = SharesShareTokenRouteImport.update({
  id: '/shares/$shareToken',
  path: '/shares/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/$workspaceId/',
    path: '/$workspaceId/',
    getParentRoute: () => AuthenticatedWorkspacesRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdTabRoute =
  AuthenticatedWorkspacesWorkspaceIdTabRouteImport.update({
    id: '/$workspaceId/$tab',
    path: '/$workspaceId/$tab',
    getParentRoute: () => AuthenticatedWorkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/shares/$shareToken': typeof SharesShareTokenRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/$tab': typeof AuthenticatedWorkspacesWorkspaceIdTabRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shares/$shareToken': typeof SharesShareTokenRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/$tab': typeof AuthenticatedWorkspacesWorkspaceIdTabRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/shares/$shareToken': typeof SharesShareTokenRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$workspaceId/$tab': typeof AuthenticatedWorkspacesWorkspaceIdTabRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/workspaces'
    | '/shares/$shareToken'
    | '/workspaces/'
    | '/workspaces/$workspaceId/$tab'
    | '/workspaces/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/shares/$shareToken'
    | '/workspaces'
    | '/workspaces/$workspaceId/$tab'
    | '/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/workspaces'
    | '/shares/$shareToken'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$workspaceId/$tab'
    | '/_authenticated/workspaces/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SharesShareTokenRoute: typeof SharesShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shares/$shareToken': {
      id: '/shares/$shareToken'
      path: '/shares/$shareToken'
      fullPath: '/shares/$shareToken'
      preLoaderRoute: typeof SharesShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRoute
    }
    '/_authenticated/workspaces/$workspaceId/$tab': {
      id: '/_authenticated/workspaces/$workspaceId/$tab'
      path: '/$workspaceId/$tab'
      fullPath: '/workspaces/$workspaceId/$tab'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdTabRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRoute
    }
  }
}

interface AuthenticatedWorkspacesRouteChildren {
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedWorkspacesWorkspaceIdTabRoute: typeof AuthenticatedWorkspacesWorkspaceIdTabRoute
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
}

const AuthenticatedWorkspacesRouteChildren: AuthenticatedWorkspacesRouteChildren =
  {
    AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdTabRoute:
      AuthenticatedWorkspacesWorkspaceIdTabRoute,
    AuthenticatedWorkspacesWorkspaceIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdIndexRoute,
  }

const AuthenticatedWorkspacesRouteWithChildren =
  AuthenticatedWorkspacesRoute._addFileChildren(
    AuthenticatedWorkspacesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SharesShareTokenRoute: SharesShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
